export const GET_REPOSITORY = "GET_REPOSITORY";
export const ADD_REPOSITORY = "ADD_REPOSITORY";
export const REMOVE_REPOSITORY = "REMOVE_REPOSITORY";
export const LOAD_REPOSITORY_LANGUAGES = "LOAD_REPOSITORY_LANGUAGES";
export const SET_REPOSITORY_LANGUAGES = "SET_REPOSITORY_LANGUAGES";
